# Generated by Selenium IDE
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys


class TestDashboardtest2:

    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_dashboardtest2(self):
        self.driver.get("https://memoretos.atoligue.uber.space/login/")

        self.driver.find_element(By.ID, "user").click()
        self.driver.find_element(By.ID, "user").send_keys("Pedro Gutierrez")

        self.driver.find_element(By.ID, "pass").click()
        self.driver.find_element(By.ID, "pass").send_keys("12345678")

        self.driver.find_element(By.CSS_SELECTOR, ".btn-entrar").click()

        element = self.driver.find_element(By.CSS_SELECTOR, ".class-btn")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()

        self.driver.find_element(By.CSS_SELECTOR, ".search-input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".search-input").send_keys("Grupo 1")

        self.driver.find_element(By.CSS_SELECTOR, ".class-btn:nth-child(2)").click()
        self.driver.find_element(By.LINK_TEXT, "←").click()

        self.driver.find_element(By.LINK_TEXT, "Partidas recientes").click()
        self.driver.find_element(By.CSS_SELECTOR, ".search-input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".search-input").send_keys("testfinal")
        self.driver.find_element(By.CSS_SELECTOR, ".search-input").send_keys(Keys.ENTER)

        self.driver.find_element(By.LINK_TEXT, "←").click()

        self.driver.find_element(By.LINK_TEXT, "Detalles del jugador").click()
        self.driver.find_element(By.CSS_SELECTOR, ".search-input").click()
        self.driver.find_element(By.CSS_SELECTOR, ".search-input").send_keys("maria_lopez")
        self.driver.find_element(By.CSS_SELECTOR, ".search-input").send_keys(Keys.ENTER)

        self.driver.find_element(By.LINK_TEXT, "←").click()

        element = self.driver.find_element(By.LINK_TEXT, "Gráficas")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()

        self.driver.find_element(By.LINK_TEXT, "Gráficas").click()

        element = self.driver.find_element(By.LINK_TEXT, "←")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).click_and_hold().perform()

        element = self.driver.find_element(By.LINK_TEXT, "←")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()

        element = self.driver.find_element(By.LINK_TEXT, "←")
        actions = ActionChains(self.driver)
        actions.move_to_element(element).release().perform()

        self.driver.find_element(By.LINK_TEXT, "←").click()