# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    self.driver.get("https://memoretos.atoligue.uber.space/registro/")
    self.driver.set_window_size(1152, 686)
    self.driver.find_element(By.ID, "reg-user").click()
    self.driver.find_element(By.CSS_SELECTOR, "body").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-entrar").click()
    self.driver.find_element(By.ID, "reg-user").send_keys("Pedro Gutierrez")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-entrar").click()
    self.driver.find_element(By.ID, "reg-mail").send_keys("a01234")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-entrar").click()
    self.driver.find_element(By.ID, "reg-mail").click()
    self.driver.find_element(By.ID, "reg-mail").send_keys("a0123456@tec.mx")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-entrar").click()
    self.driver.find_element(By.ID, "reg-pass").send_keys("12345678")
    self.driver.find_element(By.ID, "reg-rol").click()
    dropdown = self.driver.find_element(By.ID, "reg-rol")
    dropdown.find_element(By.XPATH, "//option[. = 'Maestro']").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-entrar").click()
    assert self.driver.switch_to.alert.text == "¡Registro exitoso! Ya puedes iniciar sesión."
    self.driver.find_element(By.ID, "user").click()
    self.driver.find_element(By.ID, "user").send_keys("Pedro Gutierrez")
    self.driver.find_element(By.ID, "pass").click()
    self.driver.find_element(By.ID, "pass").send_keys("12345678")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-entrar").click()
    assert self.driver.switch_to.alert.text == "¡Bienvenido, profesor!"
    self.driver.find_element(By.CSS_SELECTOR, ".class-btn:nth-child(2)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".class-btn:nth-child(3)").click()
  
